// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Platform.Api.Data;

#nullable disable

namespace Platform.Api.Migrations
{
    [DbContext(typeof(PlatformContext))]
    [Migration("20260303173346_AddProjectMembers")]
    partial class AddProjectMembers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("Platform.Api.Models.Element", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArchitectId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Bim7aaCategory")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Bim7aaSubcategory")
                        .HasColumnType("TEXT");

                    b.Property<string>("BuildingComponents")
                        .HasColumnType("TEXT");

                    b.Property<string>("BuildingPartAnalysis")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Entreprise")
                        .HasColumnType("TEXT");

                    b.Property<string>("FireClass")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Responsibility")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("SelfWeight")
                        .HasColumnType("decimal(10,3)");

                    b.Property<string>("SoundRequirement")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TypeNumber")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("UValue")
                        .HasColumnType("decimal(10,4)");

                    b.Property<string>("Unit")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Work")
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkDescriptionNumber")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ArchitectId");

                    b.ToTable("Elements");
                });

            modelBuilder.Entity("Platform.Api.Models.ElementProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ElementId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ElementId");

                    b.HasIndex("ProductId");

                    b.ToTable("ElementProducts");
                });

            modelBuilder.Entity("Platform.Api.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AcousticRating")
                        .HasColumnType("TEXT");

                    b.Property<string>("BimUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CeDeclarationUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Certifications")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("DatasheetUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeclaredUnit")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EpdUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("FireCertificateUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("FireRating")
                        .HasColumnType("TEXT");

                    b.Property<string>("FireResistance")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("GwpA1A3")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("GwpB4")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("GwpB6")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("GwpC3")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("GwpC4")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("Height")
                        .HasColumnType("TEXT");

                    b.Property<string>("InstallationGuideUrl")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Length")
                        .HasColumnType("TEXT");

                    b.Property<int>("ManufacturerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("SoundAbsorptionAlphaW")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SoundReductionRw")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SoundReductionRwCCtr")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SoundTestReportUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("ThermalPerformance")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Thickness")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("WeightPerUnit")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Width")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsPublished");

                    b.HasIndex("ManufacturerId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Platform.Api.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArchitectId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ArchitectId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("Platform.Api.Models.ProjectElement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("ElementId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("GroupId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ElementId");

                    b.HasIndex("GroupId");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectElements");
                });

            modelBuilder.Entity("Platform.Api.Models.ProjectGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectGroups");
                });

            modelBuilder.Entity("Platform.Api.Models.ProjectProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("GroupId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("ProductId");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectProducts");
                });

            modelBuilder.Entity("Platform.Api.Models.SavedProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArchitectId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("ArchitectId", "ProductId")
                        .IsUnique();

                    b.ToTable("SavedProducts");
                });

            modelBuilder.Entity("Platform.Api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Bio")
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LinkedIn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Website")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Platform.Api.Models.Element", b =>
                {
                    b.HasOne("Platform.Api.Models.User", "Architect")
                        .WithMany()
                        .HasForeignKey("ArchitectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Architect");
                });

            modelBuilder.Entity("Platform.Api.Models.ElementProduct", b =>
                {
                    b.HasOne("Platform.Api.Models.Element", "Element")
                        .WithMany("ElementProducts")
                        .HasForeignKey("ElementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Platform.Api.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Element");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Platform.Api.Models.Product", b =>
                {
                    b.HasOne("Platform.Api.Models.User", "Manufacturer")
                        .WithMany()
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manufacturer");
                });

            modelBuilder.Entity("Platform.Api.Models.Project", b =>
                {
                    b.HasOne("Platform.Api.Models.User", "Architect")
                        .WithMany()
                        .HasForeignKey("ArchitectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Architect");
                });

            modelBuilder.Entity("Platform.Api.Models.ProjectElement", b =>
                {
                    b.HasOne("Platform.Api.Models.Element", "Element")
                        .WithMany("ProjectElements")
                        .HasForeignKey("ElementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Platform.Api.Models.ProjectGroup", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Platform.Api.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Element");

                    b.Navigation("Group");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Platform.Api.Models.ProjectGroup", b =>
                {
                    b.HasOne("Platform.Api.Models.Project", "Project")
                        .WithMany("Groups")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Platform.Api.Models.ProjectProduct", b =>
                {
                    b.HasOne("Platform.Api.Models.ProjectGroup", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Platform.Api.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Platform.Api.Models.Project", "Project")
                        .WithMany("ProjectProducts")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Product");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Platform.Api.Models.SavedProduct", b =>
                {
                    b.HasOne("Platform.Api.Models.User", "Architect")
                        .WithMany()
                        .HasForeignKey("ArchitectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Platform.Api.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Architect");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Platform.Api.Models.Element", b =>
                {
                    b.Navigation("ElementProducts");

                    b.Navigation("ProjectElements");
                });

            modelBuilder.Entity("Platform.Api.Models.Project", b =>
                {
                    b.Navigation("Groups");

                    b.Navigation("ProjectProducts");
                });
#pragma warning restore 612, 618
        }
    }
}
